# Generated by Django 6.1 on 2026-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=200)),
                ('kind', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(choices=[('order_payment', 'Order payment'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual adjustment')], max_length=30)),
                ('source_id', models.CharField(db_index=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor_id', 'kind'], name='vendor_wall_vendor__bf6634_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor_id', 'kind', 'source_type', 'source_id'), name='unique_wallet_entry_per_source')],
            },
        ),
    ]
