# Generated by Django 6.1 on 2026-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayoutDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('type', models.CharField(choices=[('till', 'Till'), ('paybill', 'Paybill')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutDestinationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=200)),
                ('old_type', models.CharField(blank=True, max_length=10, null=True)),
                ('old_number', models.CharField(blank=True, max_length=20, null=True)),
                ('old_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('new_type', models.CharField(max_length=10)),
                ('new_number', models.CharField(max_length=20)),
                ('new_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['vendor_id', '-changed_at'], name='vendor_wall_vendor__515b89_idx')],
            },
        ),
    ]
