# Generated by Django 6.1 on 2026-09-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_wallet', '0002_vendorpayoutdestination_payoutdestinationchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdestinationchange',
            name='new_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payoutdestinationchange',
            name='old_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayoutdestination',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination_type', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_account', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('originator_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='vendor_wallet.walletledgerentry')),
                ('reversal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_withdrawals', to='vendor_wallet.walletledgerentry')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['vendor_id', '-requested_at'], name='vendor_wall_vendor__b64a49_idx'), models.Index(fields=['status'], name='vendor_wall_status_114c32_idx')],
            },
        ),
    ]
