# Generated by Django 6.1 on 2026-09-16 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_wallet', '0003_payoutdestinationchange_new_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
