# Generated by Django 6.1 on 2026-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_wallet', '0004_alter_withdrawal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='new_account_number',
        ),
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='new_number',
        ),
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='new_type',
        ),
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='old_account_number',
        ),
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='old_number',
        ),
        migrations.RemoveField(
            model_name='payoutdestinationchange',
            name='old_type',
        ),
        migrations.RemoveField(
            model_name='vendorpayoutdestination',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='vendorpayoutdestination',
            name='number',
        ),
        migrations.RemoveField(
            model_name='vendorpayoutdestination',
            name='type',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='destination_account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='destination_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='destination_type',
        ),
        migrations.AddField(
            model_name='payoutdestinationchange',
            name='new_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payoutdestinationchange',
            name='old_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayoutdestination',
            name='label',
            field=models.CharField(blank=True, default='My M-Pesa', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='safaricom_fee_gmarketfy_absorbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='safaricom_fee_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='safaricom_fee_vendor_pays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutdestinationchange',
            name='new_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendorpayoutdestination',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
