"""
Django settings for Gmarketfy project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&gid@qw8mfpelvu8+t$obor0+*mobb0s_*gw5we@!gj2%yy305'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["crown-snap-slapping.ngrok-free.dev", "localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://crown-snap-slapping.ngrok-free.dev",
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",  # 👈 Live Server URL
    "http://localhost:5500",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendors_and_transactions',
    'vendors_plans',
    "vendor_wallet",
    "corsheaders"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gmarketfy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gmarketfy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate(
    ".marketfy-82c42-firebase-adminsdk-fbsvc-1f7bc811f8.json"
)

firebase_admin.initialize_app(cred)

db = firestore.client()

from decouple import config

DARAJA_CONSUMER_KEY = config('DARAJA_CONSUMER_KEY')
DARAJA_CONSUMER_SECRET = config('DARAJA_CONSUMER_SECRET')
DARAJA_PASSKEY = config('DARAJA_PASSKEY')
SHORTCODE = config('SHORTCODE')
SECURITY_CREDENTIAL = config('SECURITY_CREDENTIAL')
INITIATOR_NAME = config('INITIATOR_NAME')   
INITIATOR_PASSWORD = config('MPESA_INITIATOR_PASSWORD')
CALLBACK_URL = config('CALLBACK_URL')
PLAN_PAYMENT_CALLBACK_URL = config('PLAN_PAYMENT_CALLBACK_URL')
DARAJA_OAUTH_URL = config('DARAJA_OAUTH_URL')
DARAJA_STK_URL = config('DARAJA_STK_URL')   



# --- B2C / withdrawals ---
DARAJA_B2C_SHORTCODE = config('DARAJA_B2C_SHORTCODE', default='600192')
DARAJA_INITIATOR_NAME = config('DARAJA_INITIATOR_NAME', default='testapi')
DARAJA_SECURITY_CREDENTIAL = config('DARAJA_SECURITY_CREDENTIAL', default='')
DARAJA_B2C_URL = config('DARAJA_B2C_URL', default='https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest')
B2C_RESULT_URL = config('B2C_RESULT_URL', default='')
B2C_TIMEOUT_URL = config('B2C_TIMEOUT_URL', default='')

# Withdrawal rules
WITHDRAWAL_MIN_AMOUNT = config('WITHDRAWAL_MIN_AMOUNT', default='10')