# Generated by Django 6.0.7 on 2026-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPlans',
            fields=[
                ('plan_name', models.CharField(max_length=100)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_duration', models.IntegerField(help_text='Duration in days')),
                ('plan_description', models.TextField()),
                ('vendorId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vendorEmail', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Vendor Plan',
                'verbose_name_plural': 'Vendor Plans',
            },
        ),
    ]
