# Generated by Django 6.1 on 2026-09-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=10, unique=True)),
                ('vendor_id', models.CharField(db_index=True, max_length=200)),
                ('change_type', models.CharField(choices=[('new', 'New'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renew', 'Renew')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Initialized', 'Initialized'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Initialized', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('callback_processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors_plans.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=200)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='vendors_plans.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VendorPlans',
        ),
        migrations.AddField(
            model_name='planpayment',
            name='previous_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='vendors_plans.vendorsubscription'),
        ),
        migrations.AddIndex(
            model_name='vendorsubscription',
            index=models.Index(fields=['vendor_id', 'status'], name='vendors_pla_vendor__31acee_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vendor_id',), name='unique_active_subscription_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='planpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Initialized')), fields=('vendor_id',), name='unique_initialized_payment_per_vendor'),
        ),
    ]
