# Generated by Django 6.0.7 on 2026-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vendorId', models.CharField(max_length=100)),
                ('clientId', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('itemId', models.CharField(max_length=100)),
                ('Totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('each_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='vendorMoneySummary',
            fields=[
                ('vendorId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Vendor Money Summary',
                'verbose_name_plural': 'Vendor Money Summaries',
            },
        ),
    ]
