# Generated by Django 6.1 on 2026-08-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_and_transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=10, unique=True)),
                ('order_id', models.CharField(max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='initialized', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vender_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction_description', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='vendorMoneySummary',
        ),
    ]
