# Generated by Django 6.1 on 2026-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_and_transactions', '0002_transactions_delete_payments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='vender_id',
            new_name='vendor_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='callback_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_timing',
            field=models.CharField(default='before', max_length=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='raw_callback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_date_raw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
