# Generated by Django 6.1 on 2026-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_and_transactions', '0003_rename_vender_id_transactions_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='firestore_synced',
            field=models.BooleanField(default=False),
        ),
    ]
